spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_batch_kevin
    username: discovered1086
    password: Iofdtiger#16

  batch:
    jdbc:
      initialize-schema: always